/* eslint-disable no-undef */
const Images = {
    google: require('../assets/images/common/Frame.png'),
    answer: require('../assets/images/common/answer.png'),
    diamond: require('../assets/images/common/diamond.png'),
    heartShape: require('../assets/images/common/heartShape.png'),
    hourglass: require('../assets/images/common/hourglass.png'),
    invertedtriangle: require('../assets/images/common/invertedtriangle.png'),
    longhair: require('../assets/images/common/Longhair.png'),
    mediumhair: require('../assets/images/common/Mediumhair.png'),
    oblong: require('../assets/images/common/oblong.png'),
    ovalFace: require('../assets/images/common/ovalface.png'),
    oval: require('../assets/images/common/oval.png'),
    rectangle: require('../assets/images/common/Rectangle.png'),
    round: require('../assets/images/common/round.png'),
    shorthair: require('../assets/images/common/Shorthair.png'),
    square: require('../assets/images/common/square.png'),
    triangle: require('../assets/images/common/Triangle.png'),
    triangleFace: require('../assets/images/common/triangleFace.png'),
    downArrow: require('../assets/images/home/downArrow.png'),
    CreateUniquelooks: require('../assets/images/home/CreateUniquelooks.png'),
    Customdesign: require('../assets/images/home/Customdesign.png'),
    Refreshwardrobe: require('../assets/images/home/Refreshwardrobe.png'),
    ReuseMixnmatch: require('../assets/images/home/Reuse-Mixnmatch.png'),
    shoppingassistance: require('../assets/images/home/shoppingassistance.png'),
    call: require('../assets/images/call.png'),
    addmedia: require('../assets/images/icons/Addmedia.png'),
    attachfile: require('../assets/images/icons/attach-file.png'),
    arrow: require('../assets/images/icons/back.png'),
    close: require('../assets/images/icons/Close.png'),
    down: require('../assets/images/icons/down.png'),
    dropdownarrow: require('../assets/images/icons/dropdown-arrow.png'),
    edit: require('../assets/images/icons/edit.png'),
    linked: require('../assets/images/icons/linked.png'),
    menu: require('../assets/images/icons/Menu.png'),
    Newnotification: require('../assets/images/icons/New-notification.png'),
    pointer: require('../assets/images/icons/pointer.png'),
    ratingadded: require('../assets/images/icons/rating-added.png'),
    ratingdefault: require('../assets/images/icons/rating-default.png'),
    reportissue: require('../assets/images/icons/Report-issue.png'),
    saveprofile: require('../assets/images/icons/save-profile.png'),
    heart: require('../assets/images/icons/saved-profile.png'),
    share: require('../assets/images/icons/share.png'),
    up: require('../assets/images/icons/Up.png'),

    // user: require('../assets/images/home/user.png'),
    // book: require('../assets/images/home/book.png'),
    // applogo: require('../assets/images/common/splashLogo.png'),
    // userContact: require('../assets/images/home/userContact.png'),
    // unChecked: require('../assets/images/home/unChecked.png'),
    // checked: require('../assets/images/home/checked.png'),
    // defaultImage: require('../assets/images/common/defaultImage.png'),
    // plus: require('../assets/images/voi/plus.png'),
    // closeImage: require('../assets/images/common/closeImage.png'),
    // defaultphoto: require('../assets/images/common/defaultphoto.png'),
    // logoText: require('../assets/images/common/newLogoText.png'),
    // editLogo: require('../assets/images/home/edit.png')
}
export default Images;
